extends: '@ianwremmel'
env:
  node: true
  es6: true
parserOptions:
  sourceType: "script"
rules:
  require-jsdoc:
    - 0
  no-sync:
    - 0
  no-use-before-define:
    - 2
    - nofunc
  strict:
    - 0
